### ISSUE TITLE
Add version information

### ISSUE THREAD

**Issue by jibsen** [nemequ/munit#22]
Perhaps better left off until munit is stable, but it would be nice if there were a macro in the header that reflects the version number. This way, people who copy the files into their own project have a way of knowing which version they are using.

**Comment by nemequ** [comment]
Is https://github.com/nemequ/munit/commit/6840129129c3084675a63ccfcae2115045244015 okay?

**Comment by jibsen** [comment]
Absolutely.

**Comment by nemequ** [comment]
Okay, pushed to master.
