### ISSUE TITLE
Support for non-string parameterized test parameters

### ISSUE THREAD

**Issue by computerquip-streamlabs** [nemequ/munit#41]
It was a bit surprising this wasn't supported. I don't see an easy way (or safe way) to handle pameters that aren't strings. For instance, you can't do this:

```
static int bar_params[] = {
  0, 1, 2, 3, 4, 5, MUNIT_PARAMETERS_END
};

static MunitParameterEnum test_params[] = {
  { "bar", bar_params },
  { NULL, NULL },
};
```

Note the use of MUNIT_PARAMETERS_END since NULL would obviously not work (especially given some compilers might resolve that to 0 which is really confusing). Honestly, that wouldn't work so well either (at least, it's not ideal). I would really suggest array lengths be passed instead.

**Comment by nemequ** [comment]
I agree that it would be a nice feature. I considered this when writing µnit, but in the end it would just complicate things way too much for such a small feature.

The API would have to be altered significantly and type information added, then you would need code for parsing types from strings (remember, you can set parameter values on the command line), and you would still be limited to the types µnit supported unless you write custom parsers and generators, and at that point there isn't much benefit over just using strings and parsing them in your tests.

This is something that would work well in a language with dynamic types, or if there was some RTTI system we could use (like GLib's GValue), but I don't think it's going to happen in a small testing framework with minimal dependencies.
